# Generated by Django 4.0.3 on 2022-03-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('optionWeight', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regimenApp.questionmaster')),
            ],
        ),
    ]
