# Generated by Django 4.0.3 on 2022-03-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regimenApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmaster',
            name='shortName',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
