# Generated by Django 4.0.3 on 2022-03-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regimenApp', '0002_questionmaster_shortname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.CharField(max_length=100)),
                ('penetration', models.CharField(max_length=100)),
                ('intercourse', models.CharField(max_length=100)),
                ('completion', models.CharField(max_length=100)),
                ('satisfaction', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
