# Generated by Django 4.0.3 on 2022-03-06 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regimenApp', '0003_responsedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionmaster',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optons', to='regimenApp.questionmaster'),
        ),
    ]
