# Generated by Django 4.0.3 on 2022-03-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regimenApp', '0004_alter_optionmaster_questionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsedata',
            name='avgScore',
            field=models.FloatField(default=0.0),
        ),
    ]
